spring:
  rabbitmq:
    #host: localhost
    # push할 때는 rabbitmq가 설치된 인스턴스 IP로 세팅
    host: 10.178.0.12
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.146.0.4,10.146.0.8,10.146.0.6,10.146.0.7
      port: 9200