spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/postgresql
    # push할 때는 postgresql이 설치된 인스턴스 IP로 세팅
    url: jdbc:postgresql://10.140.0.2:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    #host: localhost
    # push할 때는 rabbitmq가 설치된 인스턴스 IP로 세팅
    host: 10.128.0.6
    username: guest
    password: guest
    port: 5672