spring:
  rabbitmq:
    #host: localhost
    # push할 때는 rabbitmq가 설치된 인스턴스 IP로 세팅
    host: 10.178.0.12
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.174.0.2,10.174.0.3,10.174.0.4,10.128.0.9
      port: 9200